#ifndef UNO_INPUT_DATA
#define UNO_INPUT_DATA

#define INPUT_UP        101
#define INPUT_DOWN      102
#define INPUT_LEFT      103
#define INPUT_RIGHT     104
#define INPUT_OK        100
#define INPUT_CANCEL    110

#define NAVIGATION_MAIN_MENU 201
#define NAVIGATION_GAME 202
#define NAVIGATION_ONLINE_GAME 203
#define NAVIGATION_SETTINGS 204
#define NAVIGATION_GAME_OVER 205
#define NAVIGATION_NETWORK_CONNECT 206
#define NAVIGATION_NETWORK_ROOMS 207
#define NAVIGATION_NETWORK_WAIT_ROOM 208

#endif //UNO_INPUT_DATA
